### ISSUE TITLE
Not all solutions are provided. 

### ISSUE THREAD

**Issue by sanjaix21** [vivekchandnirala/INT-426-and-CSE-408-Coursera-Answers#2]
Week 2 and week 3 has different questions.

**Comment by unlux** [comment]
People are getting different questions, there aren't just 2 questions for every week.
Feel free to add additional questions and answers. All efforts are appreciated. Please close this issue if resolved

**Comment by sanjaix21** [comment]
> People are getting different questions, there aren't just 2 questions for every week. Feel free to add additional questions and answers. All efforts are appreciated. Please close this issue if resolved

I have added few questions that I've got. and made a PR. 
waiting for him to merge. once he acknowledge the merge I'll close this issue

**Comment by unlux** [comment]
The PR has been merged
